# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
dnf copr enable msehnout/vsftpd -y
dnf install vsftpd -y
sed -i 's|listen=NO|listen=YES|' /etc/vsftpd/vsftpd.conf
sed -i 's|listen_ipv6|#listen_ipv6|' /etc/vsftpd/vsftpd.conf
KEY="/etc/pki/tls/private/ftp.example.key"
CERT="/etc/pki/tls/certs/ftp.example.cert"
cat >> /etc/vsftpd/vsftpd.conf << EOF
ssl_enable=YES
rsa_cert_file=${CERT}
rsa_private_key_file=${KEY}
EOF
openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=ftp.example" -keyout "${KEY}"  -out "${CERT}"
/usr/sbin/vsftpd /etc/vsftpd/vsftpd.conf
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/26-cloud-base"
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/", rsync__auto: true
  config.vm.provision "shell", inline: $script
end
